/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import autobazar.Inzerat;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Acer
 */
public class FilterDialog extends javax.swing.JDialog {

    private ArrayList<Inzerat> inzeraty;
    /**
     * Creates new form FilterDialog
     */
    public FilterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButton1.setIcon(new ImageIcon("./icons/search.png"));
    }

    public ArrayList<Inzerat> getInzeraty() {
        return inzeraty;
    }

    public void setInzeraty(ArrayList<Inzerat> inzeraty) {
        this.inzeraty = inzeraty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxZnacka = new javax.swing.JComboBox<>();
        jTextFieldRokVyrobyOD = new javax.swing.JTextField();
        jTextFieldNajazdeneKmOD = new javax.swing.JTextField();
        jTextFieldRokVyrobyDO = new javax.swing.JTextField();
        jTextFieldNajazdeneKmDO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCenaOd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCenaDo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hľadanie inzerátu");

        jComboBoxZnacka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Žiadna" }));
        jComboBoxZnacka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZnackaActionPerformed(evt);
            }
        });

        jTextFieldRokVyrobyOD.setText("jTextField1");

        jTextFieldNajazdeneKmOD.setText("jTextField3");

        jTextFieldRokVyrobyDO.setText("jTextField2");

        jTextFieldNajazdeneKmDO.setText("jTextField4");

        jLabel1.setText("Značka");

        jLabel2.setText("Rok výroby");

        jLabel3.setText("Od");

        jLabel4.setText("Do");

        jLabel5.setText("Najazdené km");

        jLabel6.setText("Od");

        jLabel7.setText("Do");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\search.png")); // NOI18N
        jButton1.setText("Hľadaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Cena");

        jLabel9.setText("Od");

        jTextFieldCenaOd.setText("jTextField1");

        jLabel10.setText("Do");

        jTextFieldCenaDo.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldRokVyrobyOD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldRokVyrobyDO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)
                        .addComponent(jComboBoxZnacka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNajazdeneKmOD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCenaOd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldCenaDo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldNajazdeneKmDO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRokVyrobyOD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRokVyrobyDO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNajazdeneKmOD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNajazdeneKmDO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCenaOd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCenaDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxZnackaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZnackaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxZnackaActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String znacka = jComboBoxZnacka.getSelectedItem().toString();
        int kmOd = Integer.parseInt(jTextFieldNajazdeneKmOD.getText());
        int kmDo = Integer.parseInt(jTextFieldNajazdeneKmDO.getText());
        int rvOd = Integer.parseInt(jTextFieldRokVyrobyOD.getText());
        int rvDo = Integer.parseInt(jTextFieldRokVyrobyDO.getText());
        int cenaOd = Integer.parseInt(jTextFieldCenaOd.getText());
        int cenaDo = Integer.parseInt(jTextFieldCenaDo.getText());
        for (Inzerat inzerat : inzeraty) {
            if(!inzerat.getKategoria().getZnacka().equalsIgnoreCase(znacka)
                    && jComboBoxZnacka.getSelectedIndex() != 0){
                inzeraty.remove(inzerat);
            }else if(inzerat.getKategoria().getNajazdeneKM() < kmOd 
                    && inzerat.getKategoria().getNajazdeneKM() > kmDo){
                inzeraty.remove(inzerat);
            }else if(inzerat.getKategoria().getRokVyroby() < rvOd 
                    && inzerat.getKategoria().getRokVyroby() > rvDo){
                inzeraty.remove(inzerat);
            }else if(inzerat.getKategoria().getCena()< cenaOd 
                    && inzerat.getKategoria().getCena() > cenaDo){
                inzeraty.remove(inzerat);
            }
        }
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxZnacka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCenaDo;
    private javax.swing.JTextField jTextFieldCenaOd;
    private javax.swing.JTextField jTextFieldNajazdeneKmDO;
    private javax.swing.JTextField jTextFieldNajazdeneKmOD;
    private javax.swing.JTextField jTextFieldRokVyrobyDO;
    private javax.swing.JTextField jTextFieldRokVyrobyOD;
    // End of variables declaration//GEN-END:variables

    void NaplnUdaje() {
        ArrayList<String> znacky = new ArrayList<>();
        for (Inzerat inzerat : inzeraty) {
            if(!znacky.contains(inzerat.getKategoria().getZnacka())) {
                znacky.add(inzerat.getKategoria().getZnacka());
            } 
        }
        for (String string : znacky) {
            jComboBoxZnacka.addItem(string);
        }
        jTextFieldNajazdeneKmDO.setText("");
        jTextFieldNajazdeneKmOD.setText("");
        jTextFieldRokVyrobyDO.setText("");
        jTextFieldRokVyrobyOD.setText("");
        jTextFieldCenaDo.setText("");
        jTextFieldCenaOd.setText("");
                
    }
}
