/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import autobazar.Autobus;
import autobazar.BatozinovyPriestor;
import autobazar.StavVozidla;
import autobazar.VlastnostiSedadiel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class NovyAutobusDialog extends javax.swing.JDialog {
    private Autobus autobus;
    private boolean upravaVozidla = false;
    /**
     * Creates new form NovyAutobus
     */
    public NovyAutobusDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (StavVozidla stav : StavVozidla.values()) {
            jComboBoxStavVozidla.addItem(stav.name());
        }  
        jButtonUlozitInzerat.setIcon(new ImageIcon("./icons/save.png"));
    }

    public boolean isUpravaVozidla() {
        return upravaVozidla;
    }

    public void setUpravaVozidla(boolean upravaVozidla) {
        this.upravaVozidla = upravaVozidla;
    }

    
    public Autobus getAutobus() {
        return autobus;
    }

    public void setAutobus(Autobus autobus) {
        this.autobus = autobus;
    }
    
    public void NaplnFormular(){
        jTextFieldCena.setText(autobus.getCena()+"");
        jTextFieldZnacka.setText(autobus.getZnacka());
        jTextFieldModel.setText(autobus.getModel());       
        jComboBoxPalivo.setSelectedItem(autobus.getPalivo());                               
        jTextFieldRokVyroby.setText(autobus.getRokVyroby()+"");
        jComboBoxStavVozidla.setSelectedItem(autobus.getStav().name());
        jTextFieldVykon.setText(autobus.getVykon()+"");
        jTextFieldPocetKM.setText(autobus.getNajazdeneKM()+"");
        jTextAreaPopis.setText(autobus.getPopis());
        
        jComboBoxNadstavba.setSelectedItem(autobus.getNadstavba());
        
        jTextFieldPocetMiest.setText(autobus.getPocetMiestNaSedenie()+"");
        
        jComboBoxNormaEmisie.setSelectedItem(autobus.getNormaEmisii());
        
        jCheckBoxStandart.setSelected(autobus.getVlastnostiSedadiel().isStandart());
        jCheckBoxPolohovatelne.setSelected(autobus.getVlastnostiSedadiel().isPolohovatelne());
        jCheckBoxPosuvne.setSelected(autobus.getVlastnostiSedadiel().isPosuvne());
        jCheckBoxNastavitelne.setSelected(autobus.getVlastnostiSedadiel().isNastavitelne());
        
        jCheckBoxZiadny.setSelected(autobus.getBatozinovyPriestor().isZiadny());        
        jCheckBoxVysoky.setSelected(autobus.getBatozinovyPriestor().isVysoky());
        jCheckBoxNosicLyzi.setSelected(autobus.getBatozinovyPriestor().isNosicLyzi()); 
        jCheckBoxKlasicky.setSelected(autobus.getBatozinovyPriestor().isKlasicky());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPocetKM = new javax.swing.JTextField();
        jComboBoxStavVozidla = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabelVar1 = new javax.swing.JLabel();
        jLabelVar3 = new javax.swing.JLabel();
        jLabelVar4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldZnacka = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonUlozitInzerat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPopis = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxPalivo = new javax.swing.JComboBox<>();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldVykon = new javax.swing.JTextField();
        jTextFieldCena = new javax.swing.JTextField();
        jTextFieldRokVyroby = new javax.swing.JTextField();
        jComboBoxNadstavba = new javax.swing.JComboBox<>();
        jCheckBoxStandart = new javax.swing.JCheckBox();
        jCheckBoxPolohovatelne = new javax.swing.JCheckBox();
        jCheckBoxPosuvne = new javax.swing.JCheckBox();
        jCheckBoxNastavitelne = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxZiadny = new javax.swing.JCheckBox();
        jCheckBoxKlasicky = new javax.swing.JCheckBox();
        jCheckBoxVysoky = new javax.swing.JCheckBox();
        jCheckBoxNosicLyzi = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDruh = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxNormaEmisie = new javax.swing.JComboBox<>();
        jTextFieldPocetMiest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridávanie autobusu");

        jTextFieldPocetKM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jComboBoxStavVozidla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setText("€");

        jLabelVar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelVar1.setText("Batožinový priestor:");

        jLabelVar3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelVar3.setText("Miest na sedenie *");

        jLabelVar4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelVar4.setText("Nadstavba *");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Značka *");

        jTextFieldZnacka.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Model *");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Výkon (kW) *");

        jButtonUlozitInzerat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonUlozitInzerat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\save.png")); // NOI18N
        jButtonUlozitInzerat.setText("Uložiť inzerát");
        jButtonUlozitInzerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozitInzeratActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Palivo *");

        jTextAreaPopis.setColumns(20);
        jTextAreaPopis.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextAreaPopis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPopis);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Cena *");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Počet najazdených kilometrov *");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setText("Popis");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Rok výroby *");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Stav *");

        jComboBoxPalivo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxPalivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "benzín", "diesel", "iné" }));
        jComboBoxPalivo.setSelectedIndex(-1);

        jTextFieldModel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jTextFieldVykon.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldVykon.setToolTipText("kW");

        jTextFieldCena.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jTextFieldRokVyroby.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jComboBoxNadstavba.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxNadstavba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Klasický", "So zvýšenou nadstavbou", "Poschodový" }));
        jComboBoxNadstavba.setSelectedIndex(-1);

        jCheckBoxStandart.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxStandart.setText("Štandardne nízke");

        jCheckBoxPolohovatelne.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxPolohovatelne.setText("Polohovateľné");
        jCheckBoxPolohovatelne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPolohovatelneActionPerformed(evt);
            }
        });

        jCheckBoxPosuvne.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxPosuvne.setText("Posuvné do uličky");

        jCheckBoxNastavitelne.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxNastavitelne.setText("Výškovo nastaviteľné");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Vlastnosti sedadiel:");

        jCheckBoxZiadny.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxZiadny.setText("Žiadny");

        jCheckBoxKlasicky.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxKlasicky.setText("Klasický");

        jCheckBoxVysoky.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxVysoky.setText("Vysoký");

        jCheckBoxNosicLyzi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBoxNosicLyzi.setText("Nosič lyží");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Druh *");

        jComboBoxDruh.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxDruh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mestský", "Medzinárodný", "Ďiaľkový", "Medzinárodný", "Mikrobus", "Minibus" }));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Norma emisií *");

        jComboBoxNormaEmisie.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxNormaEmisie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euro2", "Euro3", "Euro4", "Euro5", "Euro6" }));
        jComboBoxNormaEmisie.setSelectedIndex(-1);

        jTextFieldPocetMiest.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabelVar4)
                                    .addComponent(jTextFieldVykon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxNadstavba, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                        .addComponent(jComboBoxStavVozidla, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jTextFieldRokVyroby)
                                                    .addComponent(jComboBoxPalivo, 0, 200, Short.MAX_VALUE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jTextFieldPocetKM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxZiadny)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxKlasicky)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxVysoky)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxNosicLyzi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxDruh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelVar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPocetMiest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxNormaEmisie, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxPosuvne)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxNastavitelne))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxStandart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxPolohovatelne)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRokVyroby, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVykon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPocetKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPalivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxStavVozidla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelVar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNadstavba, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelVar3)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDruh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNormaEmisie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPocetMiest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxStandart)
                    .addComponent(jCheckBoxPolohovatelne)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxPosuvne)
                    .addComponent(jCheckBoxNastavitelne))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxZiadny)
                    .addComponent(jCheckBoxKlasicky)
                    .addComponent(jCheckBoxVysoky)
                    .addComponent(jCheckBoxNosicLyzi)
                    .addComponent(jLabelVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaciaFormularu(){
        if(jTextFieldCena.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaná cena");
            return false;
        }else if(jTextFieldZnacka.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaná značka");
            return false;
        }else if(jTextFieldModel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný model");
            return false;
        }else if(jTextFieldRokVyroby.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný rok výroby");
            return false;
        }else if(jTextFieldVykon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný výkon");
            return false;
        }else if(jTextFieldPocetKM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný počet kilometrov");
            return false;
        }else if(jComboBoxDruh.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null, "Nezadaný druh");
            return false;
        }else if(jComboBoxNormaEmisie.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný druh emisnej normy");
            return false;
        }else if(jComboBoxStavVozidla.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný stav");
            return false;
        }else if(jComboBoxPalivo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný typ paliva");
            return false;
        }else if(jTextFieldPocetMiest.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný počet miest");
            return false;
        }else if(jComboBoxNadstavba.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaná nadstavba autobusu");
            return false;
        }
        return true;
    }
    
    private void jButtonUlozitInzeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozitInzeratActionPerformed
        // TODO add your handling code here:         
        if(validaciaFormularu()){
            int cena = Integer.parseInt(jTextFieldCena.getText());
            String znacka = jTextFieldZnacka.getText();
            String model = jTextFieldModel.getText();
            int vykon = Integer.parseInt(jTextFieldVykon.getText());
            String palivo;
            if(jComboBoxPalivo.getSelectedIndex() == 2){
                //ine
                palivo = JOptionPane.showInputDialog("Zadaj názov paliva");               
            }else{
                palivo = jComboBoxPalivo.getSelectedItem().toString();
            }                       
            int rokVyroby = Integer.parseInt(jTextFieldRokVyroby.getText());
            StavVozidla stavVozidla = StavVozidla.valueOf(jComboBoxStavVozidla.getSelectedItem().toString());    
            int pocetKm = Integer.parseInt(jTextFieldPocetKM.getText());     
            String popis = "";
            popis = jTextAreaPopis.getText();   
            String druh = jComboBoxDruh.getSelectedItem().toString();
            int pocetMiest = Integer.parseInt(jTextFieldPocetMiest.getText());
            String normaEmisii = jComboBoxNormaEmisie.getSelectedItem().toString();
            String nadstavba = jComboBoxNadstavba.getSelectedItem().toString();
            VlastnostiSedadiel vlastnostiSedadiel = new VlastnostiSedadiel();
            vlastnostiSedadiel.setStandart(jCheckBoxStandart.isSelected());
            vlastnostiSedadiel.setPosuvne(jCheckBoxPosuvne.isSelected());
            vlastnostiSedadiel.setPolohovatelne(jCheckBoxPolohovatelne.isSelected());
            vlastnostiSedadiel.setNastavitelne(jCheckBoxNastavitelne.isSelected());

            BatozinovyPriestor bPriestor = new BatozinovyPriestor();
            bPriestor.setKlasicky(jCheckBoxKlasicky.isSelected());
            bPriestor.setNosicLyzi(jCheckBoxNosicLyzi.isSelected());
            bPriestor.setVysoky(jCheckBoxVysoky.isSelected());
            bPriestor.setZiadny(jCheckBoxZiadny.isSelected());
            
            if(upravaVozidla){
                autobus.setZnacka(znacka);
                autobus.setModel(model);
                autobus.setCena(cena);
                autobus.setDruh(druh);
                autobus.setNajazdeneKM(pocetKm);
                autobus.setPalivo(palivo);                
                autobus.setPopis(popis);
                autobus.setStav(stavVozidla);
                autobus.setVykon(vykon);
                autobus.setRokVyroby(rokVyroby);
                
                autobus.setPocetMiestNaSedenie(pocetMiest);
                autobus.setNadstavba(nadstavba);
                autobus.setBatozinovyPriestor(bPriestor);
                autobus.setVlastnostiSedadiel(vlastnostiSedadiel); 
                JOptionPane.showMessageDialog(null, "Informácie o autobuse boli obnovené", "Upozornenie", JOptionPane.INFORMATION_MESSAGE);   
                dispose();
            }else{
                autobus = new Autobus(druh, normaEmisii, bPriestor, nadstavba, pocetMiest, vlastnostiSedadiel, cena, model, pocetKm, palivo, rokVyroby, stavVozidla, vykon, znacka, popis);
                dispose();
            }
        }      
    }//GEN-LAST:event_jButtonUlozitInzeratActionPerformed

    private void jCheckBoxPolohovatelneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPolohovatelneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPolohovatelneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUlozitInzerat;
    private javax.swing.JCheckBox jCheckBoxKlasicky;
    private javax.swing.JCheckBox jCheckBoxNastavitelne;
    private javax.swing.JCheckBox jCheckBoxNosicLyzi;
    private javax.swing.JCheckBox jCheckBoxPolohovatelne;
    private javax.swing.JCheckBox jCheckBoxPosuvne;
    private javax.swing.JCheckBox jCheckBoxStandart;
    private javax.swing.JCheckBox jCheckBoxVysoky;
    private javax.swing.JCheckBox jCheckBoxZiadny;
    private javax.swing.JComboBox<String> jComboBoxDruh;
    private javax.swing.JComboBox<String> jComboBoxNadstavba;
    private javax.swing.JComboBox<String> jComboBoxNormaEmisie;
    private javax.swing.JComboBox<String> jComboBoxPalivo;
    private javax.swing.JComboBox<String> jComboBoxStavVozidla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelVar1;
    private javax.swing.JLabel jLabelVar3;
    private javax.swing.JLabel jLabelVar4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPopis;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldPocetKM;
    private javax.swing.JTextField jTextFieldPocetMiest;
    private javax.swing.JTextField jTextFieldRokVyroby;
    private javax.swing.JTextField jTextFieldVykon;
    private javax.swing.JTextField jTextFieldZnacka;
    // End of variables declaration//GEN-END:variables
}
