/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import autobazar.Automobil;
import autobazar.StavVozidla;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class NovyAutomobilDialog extends javax.swing.JDialog {
    private Automobil automobil;
    private boolean upravaVozidla = false;
    /**
     * Creates new form NovyAutomobilDialog
     */
    public NovyAutomobilDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (StavVozidla stav : StavVozidla.values()) {
            jComboBoxStavVozidla.addItem(stav.name());
        }     
        jButtonUlozitInzerat.setIcon(new ImageIcon("./icons/save.png"));
    }

    public Automobil getAutomobil() {
        return automobil;
    }

    public void setAutomobil(Automobil automobil) {
        this.automobil = automobil;
    }

    public boolean isUpravaVozidla() {
        return upravaVozidla;
    }

    public void setUpravaVozidla(boolean upravaVozidla) {
        this.upravaVozidla = upravaVozidla;
    }
    
    
    
    public void NaplnFormular(){
        jTextFieldCena.setText(automobil.getCena()+"");
        jTextFieldZnacka.setText(automobil.getZnacka());
        jTextFieldModel.setText(automobil.getModel());       
        jComboBoxPalivo.setSelectedItem(automobil.getPalivo());                               
        jTextFieldRokVyroby.setText(automobil.getRokVyroby()+"");
        jComboBoxStavVozidla.setSelectedItem(automobil.getStav().name());
        jTextFieldVykon.setText(automobil.getVykon()+"");
        jTextFieldPocetKM.setText(automobil.getNajazdeneKM()+"");
        jComboBoxPocetDveri.setSelectedItem(automobil.getPocetDveri()+"");
        jComboBoxPocetSedadiel.setSelectedItem(automobil.getPocetSedadiel()+"");
        jTextFieldKaroseria.setText(automobil.getKaroseria());
        jTextAreaPopis.setText(automobil.getPopis());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPocetKM = new javax.swing.JTextField();
        jComboBoxStavVozidla = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabelVar1 = new javax.swing.JLabel();
        jLabelVar2 = new javax.swing.JLabel();
        jLabelVar3 = new javax.swing.JLabel();
        jTextFieldKaroseria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldZnacka = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPopis = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxPalivo = new javax.swing.JComboBox<>();
        jTextFieldModel = new javax.swing.JTextField();
        jComboBoxPocetSedadiel = new javax.swing.JComboBox<>();
        jTextFieldVykon = new javax.swing.JTextField();
        jComboBoxPocetDveri = new javax.swing.JComboBox<>();
        jTextFieldCena = new javax.swing.JTextField();
        jTextFieldRokVyroby = new javax.swing.JTextField();
        jButtonUlozitInzerat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridanie automobilu");

        jTextFieldPocetKM.setText("198000");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("€");

        jLabelVar1.setText("Karoséria *");

        jLabelVar2.setText("Počet dverí *");

        jLabelVar3.setText("Počet sedadiel *");

        jTextFieldKaroseria.setText("sedan");

        jLabel9.setText("Značka *");

        jTextFieldZnacka.setText("Fiat");

        jLabel10.setText("Model *");

        jLabel11.setText("Výkon *");

        jLabel12.setText("Palivo *");

        jTextAreaPopis.setColumns(20);
        jTextAreaPopis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPopis);

        jLabel13.setText("Cena *");

        jLabel14.setText("Pocet kilometrov *");

        jLabel19.setText("Popis");

        jLabel15.setText("Rok výroby *");

        jLabel16.setText("Stav *");

        jComboBoxPalivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "benzín", "diesel", "iné" }));

        jTextFieldModel.setText("Bravo");

        jComboBoxPocetSedadiel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

        jTextFieldVykon.setText("65");
        jTextFieldVykon.setToolTipText("kW");

        jComboBoxPocetDveri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "5" }));
        jComboBoxPocetDveri.setToolTipText("Počet dverí");
        jComboBoxPocetDveri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPocetDveriActionPerformed(evt);
            }
        });

        jTextFieldRokVyroby.setText("2000");

        jButtonUlozitInzerat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\save.png")); // NOI18N
        jButtonUlozitInzerat.setText("Uložiť");
        jButtonUlozitInzerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozitInzeratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBoxStavVozidla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxPocetSedadiel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxPocetDveri, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelVar3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldVykon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPocetKM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(386, 386, 386))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14))))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldRokVyroby)
                                    .addComponent(jComboBoxPalivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVar1)
                                    .addComponent(jTextFieldKaroseria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRokVyroby, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVykon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPocetKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPalivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxStavVozidla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelVar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPocetSedadiel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelVar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPocetDveri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelVar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldKaroseria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaciaFormularu(){
        if(jTextFieldCena.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaná cena automobilu");
            return false;
        }else if(jTextFieldZnacka.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaná značka automobilu");
            return false;
        }else if(jTextFieldModel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný model automobilu");
            return false;
        }else if(jTextFieldRokVyroby.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný rok výroby automobilu");
            return false;
        }else if(jTextFieldVykon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný výkon automobilu");
            return false;
        }else if(jTextFieldPocetKM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný počet kilometrov automobilu");
            return false;
        }else if(jTextFieldKaroseria.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný typ karosérie automobilu");
            return false;
        }else if(jComboBoxPocetSedadiel.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný počet sedadiel automobilu");
            return false;
        }else if(jComboBoxStavVozidla.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný stav automobilu");
            return false;
        }else if(jComboBoxPocetDveri.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný počet dverí automobilu");
            return false;
        }else if(jComboBoxPalivo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný typ paliva automobilu");
            return false;
        }
        return true;
    }
    
    private void jComboBoxPocetDveriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPocetDveriActionPerformed
        //inicializacia premennych       
    }//GEN-LAST:event_jComboBoxPocetDveriActionPerformed

    private void jButtonUlozitInzeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozitInzeratActionPerformed
        //inicializacia premennych  
    
        if(validaciaFormularu()){
            int cena = Integer.parseInt(jTextFieldCena.getText());
            String znacka = jTextFieldZnacka.getText();
            String model = jTextFieldModel.getText();       
            String palivo = jComboBoxPalivo.getSelectedItem().toString();                               
            int rokVyroby = Integer.parseInt(jTextFieldRokVyroby.getText());
            StavVozidla stavVozidla = StavVozidla.valueOf(jComboBoxStavVozidla.getSelectedItem().toString());
            int vykon = Integer.parseInt(jTextFieldVykon.getText());
            int pocetKm = Integer.parseInt(jTextFieldPocetKM.getText());
            int pocetDveri = Integer.parseInt(jComboBoxPocetDveri.getSelectedItem().toString());
            int pocetSedadiel = Integer.parseInt(jComboBoxPocetSedadiel.getSelectedItem().toString());
            String karoseria = jTextFieldKaroseria.getText();
            String popis = "";
            popis = jTextAreaPopis.getText();
            if(upravaVozidla){
                automobil.setZnacka(znacka);
                automobil.setModel(model);
                automobil.setCena(cena);
                automobil.setKaroseria(karoseria);
                automobil.setNajazdeneKM(pocetKm);
                automobil.setPalivo(palivo);
                automobil.setPocetDveri(pocetDveri);
                automobil.setPopis(popis);
                automobil.setPocetSedadiel(pocetSedadiel);
                automobil.setStav(stavVozidla);
                automobil.setVykon(vykon);
                automobil.setRokVyroby(rokVyroby);
                JOptionPane.showMessageDialog(null, "Informácie o automobile boli obnovené", "Upozornenie", JOptionPane.INFORMATION_MESSAGE);   
                dispose();
            }else{
                //vytvorenie instancie automobil
                automobil = new Automobil(karoseria, pocetDveri, pocetSedadiel, cena, model, pocetKm, palivo, rokVyroby, stavVozidla, vykon, znacka, popis);
                dispose();
            }
        }      
    }//GEN-LAST:event_jButtonUlozitInzeratActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUlozitInzerat;
    private javax.swing.JComboBox<String> jComboBoxPalivo;
    private javax.swing.JComboBox<String> jComboBoxPocetDveri;
    private javax.swing.JComboBox<String> jComboBoxPocetSedadiel;
    private javax.swing.JComboBox<String> jComboBoxStavVozidla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelVar1;
    private javax.swing.JLabel jLabelVar2;
    private javax.swing.JLabel jLabelVar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPopis;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldKaroseria;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldPocetKM;
    private javax.swing.JTextField jTextFieldRokVyroby;
    private javax.swing.JTextField jTextFieldVykon;
    private javax.swing.JTextField jTextFieldZnacka;
    // End of variables declaration//GEN-END:variables
}
