package gui;

import autobazar.Motocykel;
import autobazar.StavVozidla;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Dialogove okno pre vytvorenie motocykla.
 * @author Jakub Cachovan
 */
public class NovyMotocykelDialog extends javax.swing.JDialog {
    
    private Motocykel motocykel;
    private boolean upravaVozidla = false;
    /**
     * Creates new form NovyMotocykelDialog
     * @param parent parent
     * @param modal modal
     */
    public NovyMotocykelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (StavVozidla stav : StavVozidla.values()) {
            jComboBoxStav.addItem(stav.name());
        }    
        jButtonUlozitInzerat.setIcon(new ImageIcon("./icons/save.png"));
    }

    /**
     * Indikátor úpravy motocykla.
     * @return true/false
     */
    public boolean isUpravaVozidla() {
        return upravaVozidla;
    }

    /**
     * Setter pre indikátor úpravy motocykla.
     * @param upravaVozidla true/false
     */
    public void setUpravaVozidla(boolean upravaVozidla) {
        this.upravaVozidla = upravaVozidla;
    }


    /**
     * Setter pre atribut motocykel.
     * @param motocykel - objekt typu Motocykel
     */    
    public void setMotocykel(Motocykel motocykel) {
        this.motocykel = motocykel;
    }

    /**
     * Getter pre atribut motocykel
     * @return - objekt typu Motocykel
     */
    public Motocykel getMotocykel() {
        return motocykel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPocetKM = new javax.swing.JTextField();
        jComboBoxStav = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButtonUlozitInzerat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPopis = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxDruh = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxPalivo = new javax.swing.JComboBox<>();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldVykon = new javax.swing.JTextField();
        jTextFieldCena = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRokVyroby = new javax.swing.JTextField();
        jTextFieldZnacka = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldObjem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nový motocykel");

        jTextFieldPocetKM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jComboBoxStav.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel17.setText("€");

        jButtonUlozitInzerat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonUlozitInzerat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\save.png")); // NOI18N
        jButtonUlozitInzerat.setText("Uložiť inzerát");
        jButtonUlozitInzerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozitInzeratActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Palivo *");

        jTextAreaPopis.setColumns(20);
        jTextAreaPopis.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextAreaPopis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPopis);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Cena *");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Počet najazdených kilometrov *");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Druh *");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setText("Popis");

        jComboBoxDruh.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxDruh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Štvorkolky", "Snežné skútre", "Vodné skútre", "Skútre", "Scross/Enduro/Supermoto", "SuperSport", "Chopper", "Naked", "Tourist", "Minibike", "Motokáry", "Trojkolky", "Buginy", "Mopedy", "Veterány" }));
        jComboBoxDruh.setSelectedIndex(-1);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Rok výroby *");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Stav *");

        jComboBoxPalivo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxPalivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "benzín", "diesel", "iné" }));

        jTextFieldModel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jTextFieldVykon.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldVykon.setToolTipText("kW");

        jTextFieldCena.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Značka *");

        jTextFieldRokVyroby.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jTextFieldZnacka.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Model * ");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Výkon (kW) *");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Objem válcov (ccm) *");

        jTextFieldObjem.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextFieldVykon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jComboBoxStav, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxDruh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextFieldRokVyroby)
                                            .addComponent(jComboBoxPalivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextFieldPocetKM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldObjem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addComponent(jLabel13))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRokVyroby, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVykon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPocetKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPalivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxStav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDruh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldObjem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(40, 40, 40)
                .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Validácia formuláru pre úpravu motocykla.
     * @return true/false
     */
    public boolean validaciaFormularu(){
        if(jTextFieldCena.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaná cena motocyklu");
            return false;
        }else if(jTextFieldZnacka.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaná značka motocyklu");
            return false;
        }else if(jTextFieldModel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný model motocyklu");
            return false;
        }else if(jTextFieldRokVyroby.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný rok výroby motocyklu");
            return false;
        }else if(jTextFieldVykon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný výkon motocyklu");
            return false;
        }else if(jTextFieldPocetKM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nezadaný počet kilometrov motocyklu");
            return false;
        }else if(jComboBoxDruh.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null, "Nezadaný druh motocyklu");
            return false;
        }else if(jComboBoxStav.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný počet motocyklu");
            return false;
        }else if(jComboBoxPalivo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nezadaný typ paliva motocyklu");
            return false;
        }
        return true;
    }
    
    /**
     * Inicializácia dát do formulárov, v prípade že sa jedná o úpravu.
     */
    public void NaplnFormular(){
        jTextFieldCena.setText(motocykel.getCena()+"");
        jTextFieldZnacka.setText(motocykel.getZnacka());
        jTextFieldModel.setText(motocykel.getModel());       
        jComboBoxPalivo.setSelectedItem(motocykel.getPalivo());                               
        jTextFieldRokVyroby.setText(motocykel.getRokVyroby()+"");
        jComboBoxStav.setSelectedItem(motocykel.getStav().name());
        jTextFieldVykon.setText(motocykel.getVykon()+"");
        jTextFieldPocetKM.setText(motocykel.getNajazdeneKM()+"");      
        jTextAreaPopis.setText(motocykel.getPopis());
        
        jTextFieldObjem.setText(motocykel.getObjemValcov()+"");
        jComboBoxDruh.setSelectedItem(motocykel.getDruh());
    }
    
    /**
     * Uloženie kategorie vozidla pre inzerát.
     * @param evt 
     */
    private void jButtonUlozitInzeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozitInzeratActionPerformed
        // TODO add your handling code here:      
        if(validaciaFormularu()){
            int cena = Integer.parseInt(jTextFieldCena.getText());
            String znacka = jTextFieldZnacka.getText();
            String model = jTextFieldModel.getText();
            int rokVyroby = Integer.parseInt(jTextFieldRokVyroby.getText());
            String palivo;                             
            StavVozidla stavVozidla = StavVozidla.valueOf(jComboBoxStav.getSelectedItem().toString());
            int vykon = Integer.parseInt(jTextFieldVykon.getText());
            int pocetKm = Integer.parseInt(jTextFieldPocetKM.getText());
            String druh = jComboBoxDruh.getSelectedItem().toString();
            int objemValcov = Integer.parseInt(jTextFieldObjem.getText());
            String popis = "";           
            if(jComboBoxPalivo.getSelectedIndex() == 2){
                //ine
                palivo = JOptionPane.showInputDialog("Zadaj názov paliva");               
            }else{
                palivo = jComboBoxPalivo.getSelectedItem().toString();
            }  
            popis = jTextAreaPopis.getText();  
            
            if(upravaVozidla){
                motocykel.setCena(cena);
                motocykel.setDruh(druh);
                motocykel.setModel(model);
                motocykel.setNajazdeneKM(pocetKm);
                motocykel.setObjemValcov(objemValcov);
                motocykel.setPalivo(palivo);
                motocykel.setPopis(popis);
                motocykel.setRokVyroby(rokVyroby);
                motocykel.setStav(stavVozidla);
                motocykel.setVykon(vykon);
                motocykel.setZnacka(znacka);
                JOptionPane.showMessageDialog(null, "Informácie o motocykli boli obnovené", "Upozornenie", JOptionPane.INFORMATION_MESSAGE);   
                dispose();
            }else{
                motocykel = new Motocykel(druh, objemValcov, cena, model, pocetKm, palivo, rokVyroby, stavVozidla, vykon, znacka, popis);
                dispose();
            }          
        }      
    }//GEN-LAST:event_jButtonUlozitInzeratActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUlozitInzerat;
    private javax.swing.JComboBox<String> jComboBoxDruh;
    private javax.swing.JComboBox<String> jComboBoxPalivo;
    private javax.swing.JComboBox<String> jComboBoxStav;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPopis;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldObjem;
    private javax.swing.JTextField jTextFieldPocetKM;
    private javax.swing.JTextField jTextFieldRokVyroby;
    private javax.swing.JTextField jTextFieldVykon;
    private javax.swing.JTextField jTextFieldZnacka;
    // End of variables declaration//GEN-END:variables
}
