/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import autobazar.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Acer
 */
public class UpravitInzeratDialog extends javax.swing.JDialog {
    private Inzerat inzerat;
    private boolean upravaPredajcu = false;
    private boolean upravaVozidla = false;
    /**
     * Creates new form UpravitInzeratDialog2
     */
    public UpravitInzeratDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonUpravitPredajcu.setIcon(new ImageIcon("./icons/userM.png"));
        jButtonUpravitVozidlo.setIcon(new ImageIcon("./icons/car.png"));
    }

    public Inzerat getInzerat() {
        return inzerat;
    }

    public void setInzerat(Inzerat inzerat) {
        this.inzerat = inzerat;
    }

    public boolean isUpravaPredajcu() {
        return upravaPredajcu;
    }

    public boolean isUpravaVozidla() {
        return upravaVozidla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpravitPredajcu = new javax.swing.JButton();
        jButtonUpravitVozidlo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upraviť inzerát");

        jButtonUpravitPredajcu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonUpravitPredajcu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\userM.png")); // NOI18N
        jButtonUpravitPredajcu.setText("Upraviť predajcu");
        jButtonUpravitPredajcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpravitPredajcuActionPerformed(evt);
            }
        });

        jButtonUpravitVozidlo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonUpravitVozidlo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\car.png")); // NOI18N
        jButtonUpravitVozidlo.setText("Upraviť vozidlo");
        jButtonUpravitVozidlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpravitVozidloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUpravitPredajcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpravitVozidlo, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUpravitPredajcu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUpravitVozidlo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpravitPredajcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpravitPredajcuActionPerformed
        upravaPredajcu = true;
        NovyPredajcaDialog predajcaDialog = new NovyPredajcaDialog(null, true);
        predajcaDialog.setLocationRelativeTo(null);       
        predajcaDialog.setPredajca(inzerat.getPredajca());
        predajcaDialog.NaplnFormular();
        predajcaDialog.setUpravaPredajcu(upravaPredajcu);
        predajcaDialog.setTitle("Úprava predajcu");
        predajcaDialog.setVisible(true);
        //if(!Update.upravitPredajcu(inzerat.getPredajca(), Aplikacia.DbPath))
            //JOptionPane.showMessageDialog(null, "Chyba pri upravovani predajcu v DB");
        dispose();
    }//GEN-LAST:event_jButtonUpravitPredajcuActionPerformed

    private void jButtonUpravitVozidloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpravitVozidloActionPerformed
        upravaVozidla = true;
        switch(inzerat.getInstanceKategoria()){
            case 1:
                //Automobil
                NovyAutomobilDialog autoDialog = new NovyAutomobilDialog(null, true);
                autoDialog.setLocationRelativeTo(null);
                Automobil auto = (Automobil)inzerat.getKategoria();
                autoDialog.setAutomobil(auto);
                autoDialog.setUpravaVozidla(upravaVozidla);
                autoDialog.NaplnFormular();
                autoDialog.setTitle("Úprava automobilu");
                autoDialog.setVisible(true);
                dispose();
                break;
                
            case 2:
                //Autobus
                NovyAutobusDialog autobusDialog = new NovyAutobusDialog(null, true);
                autobusDialog.setLocationRelativeTo(null);
                Autobus autobus = (Autobus)inzerat.getKategoria();
                autobusDialog.setAutobus(autobus);
                autobusDialog.setUpravaVozidla(upravaVozidla);
                autobusDialog.NaplnFormular();
                autobusDialog.setTitle("Úprava autobusu");
                autobusDialog.setVisible(true);
                dispose();
                break;
            case 3:
                //Motocykel
                NovyMotocykelDialog motoDialog = new NovyMotocykelDialog(null, true);
                motoDialog.setLocationRelativeTo(null);
                Motocykel moto = (Motocykel)inzerat.getKategoria();
                motoDialog.setMotocykel(moto);
                motoDialog.setUpravaVozidla(upravaVozidla);
                motoDialog.NaplnFormular();
                motoDialog.setTitle("Úprava motocyklu");
                motoDialog.setVisible(true);
                dispose();
                break;
            case 4:
               //Nakladne auto
                NovyNakladakDialog nakladneDialog = new NovyNakladakDialog(null, true);
                nakladneDialog.setLocationRelativeTo(null);
                NakladneAuto nakladne = (NakladneAuto)inzerat.getKategoria();
                nakladneDialog.setNakladne(nakladne);
                nakladneDialog.setUpravaVozidla(upravaVozidla);
                nakladneDialog.NaplnFormular();
                nakladneDialog.setTitle("Úprava nákladného auta");
                nakladneDialog.setVisible(true);
                dispose();
               break;          
        }
    }//GEN-LAST:event_jButtonUpravitVozidloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpravitPredajcu;
    private javax.swing.JButton jButtonUpravitVozidlo;
    // End of variables declaration//GEN-END:variables
}
