package gui;

import autobazar.Kategoria;
import autobazar.Predajca;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Dialogove okno pre vytvorenie inzeratu.
 * @author Jakub Cachovan
 */
public final class VytvoritInzeratDialog extends javax.swing.JDialog {

    private ArrayList<Predajca> existujuciPredajcovia;
    private Predajca predajca;
    private Kategoria kategoria;           
    /**
     * Creates new form VytvoritInzeratDialog
     * @param parent
     * @param modal
     */
    public VytvoritInzeratDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel9.setVisible(false);
        jLabelHlaska.setVisible(false);
        jLabelDetail.setVisible(false);
        jLabelDetailText.setVisible(false);
        initIcons();
    }
    
    /**
     * Inicializácia ikon pre tlačidla a labely.
     */
    public void initIcons(){
        jButtonHladaj.setIcon(new ImageIcon("./icons/search.png"));
        jButtonNovyPredajca.setIcon(new ImageIcon("./icons/newUser.png"));
        jButtonObnovit.setIcon(new ImageIcon("./icons/obnovit.png"));
        jButtonPridajExistujuceho.setIcon(new ImageIcon("./icons/save.png"));
        jButtonUlozitInzerat.setIcon(new ImageIcon("./icons/save.png"));
        
        jToggleButtonAutomobil.setIcon(new ImageIcon("./icons/automobil.png"));
        jToggleButtonAutobus.setIcon(new ImageIcon("./icons/autobus.png"));
        jToggleButtonMotocykel.setIcon(new ImageIcon("./icons/motocykel.png"));
        jToggleButtonNakladne.setIcon(new ImageIcon("./icons/nakladne.png"));
        
        jLabel1.setIcon(new ImageIcon("./icons/userM.png"));
        jLabel9.setIcon(new ImageIcon("./icons/aktivne.png"));
        jLabelDetail.setIcon(new ImageIcon("./icons/user.png"));
    }
    
    /**
     * Naplnenie tabulky existujucich predajcov.
     */
    public void NaplnTableExistujucichPredajcov(){
        DefaultTableModel m = (DefaultTableModel)jTableExistujuciPredajcovia.getModel();
        m.setRowCount(0); // pre istotu premazeme tabulku aby ked pouzijeme metodu znovu nedochadzalo k duplicitam
        for (Predajca p : existujuciPredajcovia) {
            String [] row = {p.getEmail(), p.getMeno(), p.getPriezvisko(), p.getLokalita()};
            m.addRow(row);
        }      
    }

    /**
     * Setter pre nastavenie existujuceho zoznamu predajcov.
     * @param existujuciPredajcovia 
     */
    public void setExistujuciPredajcovia(ArrayList<Predajca> existujuciPredajcovia) {
        this.existujuciPredajcovia = existujuciPredajcovia;
    }
   
    /**
     * Gettter pre objekt typu Predajca.
     * @return 
     */
    public Predajca getPredajca() {
        return predajca;
    }

    /**
     * Getter pre objekt typu Kategoria.
     * @return 
     */
    public Kategoria getKategoria() {
        return kategoria;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKategoria = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonUlozitInzerat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonNovyPredajca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExistujuciPredajcovia = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonPridajExistujuceho = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldHladany = new javax.swing.JTextField();
        jButtonHladaj = new javax.swing.JButton();
        jButtonObnovit = new javax.swing.JButton();
        jLabelHlaska = new javax.swing.JLabel();
        jLabelDetail = new javax.swing.JLabel();
        jLabelDetailText = new javax.swing.JLabel();
        jToggleButtonAutomobil = new javax.swing.JToggleButton();
        jToggleButtonMotocykel = new javax.swing.JToggleButton();
        jToggleButtonAutobus = new javax.swing.JToggleButton();
        jToggleButtonNakladne = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nový inzerát");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\userM.png")); // NOI18N
        jLabel1.setText("Predajca");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Inzerát");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Zvolte kategóriu");

        jButtonUlozitInzerat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonUlozitInzerat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\save.png")); // NOI18N
        jButtonUlozitInzerat.setText("Pridať inzerát");
        jButtonUlozitInzerat.setEnabled(false);
        jButtonUlozitInzerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozitInzeratActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\aktivne.png")); // NOI18N
        jLabel9.setText("vlozenyText");

        jButtonNovyPredajca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonNovyPredajca.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\newUser.png")); // NOI18N
        jButtonNovyPredajca.setText("Pridať nového predajcu");
        jButtonNovyPredajca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovyPredajcaActionPerformed(evt);
            }
        });

        jTableExistujuciPredajcovia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTableExistujuciPredajcovia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Meno", "Priezvisko", "Lokalita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExistujuciPredajcovia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExistujuciPredajcoviaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExistujuciPredajcovia);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Alebo označte existujúceho predajcu");

        jButtonPridajExistujuceho.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonPridajExistujuceho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\aktivne.png")); // NOI18N
        jButtonPridajExistujuceho.setText("Uložiť predajcu");
        jButtonPridajExistujuceho.setEnabled(false);
        jButtonPridajExistujuceho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPridajExistujucehoActionPerformed(evt);
            }
        });

        jButtonHladaj.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonHladaj.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\search.png")); // NOI18N
        jButtonHladaj.setText("Hľadaj");
        jButtonHladaj.setToolTipText("Hľadanie podľa emailu, mena, priezviska aj lokality");
        jButtonHladaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHladajActionPerformed(evt);
            }
        });

        jButtonObnovit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\obnovit.png")); // NOI18N
        jButtonObnovit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObnovitActionPerformed(evt);
            }
        });

        jLabelHlaska.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelHlaska.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\aktivne.png")); // NOI18N
        jLabelHlaska.setText("Hláška");

        jLabelDetail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelDetail.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\user.png")); // NOI18N
        jLabelDetail.setText("Detail predajcu:");

        jLabelDetailText.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelDetailText.setText("jLabel3");

        buttonGroupKategoria.add(jToggleButtonAutomobil);
        jToggleButtonAutomobil.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\automobil.png")); // NOI18N
        jToggleButtonAutomobil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutomobilActionPerformed(evt);
            }
        });

        buttonGroupKategoria.add(jToggleButtonMotocykel);
        jToggleButtonMotocykel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\motocykel.png")); // NOI18N
        jToggleButtonMotocykel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMotocykelActionPerformed(evt);
            }
        });

        buttonGroupKategoria.add(jToggleButtonAutobus);
        jToggleButtonAutobus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\autobus.png")); // NOI18N
        jToggleButtonAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutobusActionPerformed(evt);
            }
        });

        buttonGroupKategoria.add(jToggleButtonNakladne);
        jToggleButtonNakladne.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Autobazar\\icons\\nakladne.png")); // NOI18N
        jToggleButtonNakladne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonNakladneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonObnovit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHladany, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHladaj))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNovyPredajca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonPridajExistujuceho)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelHlaska))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelDetail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelDetailText))
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jToggleButtonAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jToggleButtonMotocykel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jToggleButtonAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jToggleButtonNakladne, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonNovyPredajca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHladany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jButtonHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPridajExistujuceho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHlaska))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDetail)
                            .addComponent(jLabelDetailText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonMotocykel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonNakladne, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButtonUlozitInzerat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonObnovit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Uloženie inzerátu.
     * @param evt 
     */
    private void jButtonUlozitInzeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozitInzeratActionPerformed
        
        if(kategoria != null && predajca != null ){
           dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Niekde nastala chyba !!!");
       }
    }//GEN-LAST:event_jButtonUlozitInzeratActionPerformed

    /**
     * Vytvorenie nového predajcu pre inzerát.
     * @param evt 
     */
    private void jButtonNovyPredajcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovyPredajcaActionPerformed
        // TODO add your handling code here:
        NovyPredajcaDialog novyPredajca = new NovyPredajcaDialog(null, true);
        novyPredajca.setLocationRelativeTo(null);
        novyPredajca.setExistujuciPredajcovia(existujuciPredajcovia);
        novyPredajca.setVisible(true);
        if(novyPredajca.getPredajca() != null){
            predajca = novyPredajca.getPredajca();
            jLabelHlaska.setText("Nový predajca úspešne vytvorený");
            jLabelHlaska.setVisible(true);
            jLabelDetail.setText("Detail predajcu: ");
            jLabelDetail.setVisible(true);
            String detail = predajca.getMeno() +", " + predajca.getPriezvisko()+ ", "+ predajca.getEmail() + ", "+ predajca.getLokalita() + ", " + predajca.getTelefon();
            jLabelDetailText.setText(detail);
            jLabelDetailText.setVisible(true);
            jTableExistujuciPredajcovia.setEnabled(false);
            jButtonPridajExistujuceho.setEnabled(false);
            jButtonHladaj.setEnabled(false);
            jButtonObnovit.setEnabled(false);
            jTextFieldHladany.setEnabled(false);
        }            
    }//GEN-LAST:event_jButtonNovyPredajcaActionPerformed

    /**
     * Aktivovanie funkcionalít po kliknutí na inzerát v tabulke.
     * @param evt 
     */
    private void jTableExistujuciPredajcoviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExistujuciPredajcoviaMouseClicked
        // TODO add your handling code here:
        int selectedRow = -1;
        selectedRow = jTableExistujuciPredajcovia.getSelectedRow();
        if(selectedRow != -1){
            jButtonPridajExistujuceho.setEnabled(true);
            jLabelHlaska.setVisible(true);
            jLabelHlaska.setText("Uložte výber predajcu pre inzerát");
            jLabelHlaska.setIcon(new ImageIcon("./icons/warning.png"));       
        }
    }//GEN-LAST:event_jTableExistujuciPredajcoviaMouseClicked

    /**
     * Priradenie existujuceho predajcu pre inzerát.
     * @param evt 
     */
    private void jButtonPridajExistujucehoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPridajExistujucehoActionPerformed
        int selectedRow = jTableExistujuciPredajcovia.getSelectedRow();
        DefaultTableModel m = (DefaultTableModel)jTableExistujuciPredajcovia.getModel();
        String email = m.getValueAt(selectedRow, 0).toString();
        for (Predajca p : existujuciPredajcovia) {
            if(p.getEmail().equalsIgnoreCase(email)){
                predajca = p;
                jLabelHlaska.setText("Predajca úspešne priradený inzerátu");
                jLabelHlaska.setIcon(new ImageIcon("./icons/aktivne.png"));
                jLabelHlaska.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_jButtonPridajExistujucehoActionPerformed
 
    /**
     * Hľadanie predajcu podla vlastnosti predajcu v tabulke.
     * @param evt 
     */
    private void jButtonHladajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHladajActionPerformed
        if(!jTextFieldHladany.getText().isEmpty()){
            String zadanyText = jTextFieldHladany.getText();
            ArrayList<Predajca> filtrovanyPrejcovia = new ArrayList<>();
            for (Predajca p : existujuciPredajcovia) {
                if(p.getEmail().equalsIgnoreCase(zadanyText)
                        || p.getMeno().equalsIgnoreCase(zadanyText)
                        || p.getPriezvisko().equalsIgnoreCase(zadanyText)
                        || p.getLokalita().equalsIgnoreCase(zadanyText)){
                    filtrovanyPrejcovia.add(p);
                }
            }
            if(filtrovanyPrejcovia.size() > 0){
                DefaultTableModel m = (DefaultTableModel)jTableExistujuciPredajcovia.getModel();
                m.setRowCount(0);
                for (Predajca p : filtrovanyPrejcovia) {
                    String [] row = {p.getEmail(), p .getMeno(), p.getPriezvisko(), p.getLokalita()};
                    m.addRow(row);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Žiadna zhoda !", "Neúspech", JOptionPane.WARNING_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Najprv zadajte hladany text");
        }
    }//GEN-LAST:event_jButtonHladajActionPerformed

    /**
     * Obnovenie tabulky exisujucich predajcov.
     * @param evt 
     */
    private void jButtonObnovitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObnovitActionPerformed
        NaplnTableExistujucichPredajcov();
    }//GEN-LAST:event_jButtonObnovitActionPerformed

    /**
     * Tlačidlo pre vytvorenie automobilu.
     * @param evt 
     */
    private void jToggleButtonAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutomobilActionPerformed
        NovyAutomobilDialog autoDialog = new NovyAutomobilDialog(null, true);
        autoDialog.setLocationRelativeTo(null);
        autoDialog.setVisible(true);
        kategoria = autoDialog.getAutomobil();
        if(kategoria != null) {
            jLabel9.setText("Kategória úspešne pridaná");
            jLabel9.setVisible(true);
            jButtonUlozitInzerat.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButtonAutomobilActionPerformed

    /**
     * Tlačidlo pre vytvorenie motocykla.
     * @param evt 
     */
    private void jToggleButtonMotocykelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMotocykelActionPerformed
        NovyMotocykelDialog motoDialog = new NovyMotocykelDialog(null, true);
        motoDialog.setLocationRelativeTo(null);
        motoDialog.setVisible(true);
        kategoria = motoDialog.getMotocykel();
        if(kategoria != null){
            jLabel9.setText("Kategória úspešne pridaná");
            jLabel9.setVisible(true);
            jButtonUlozitInzerat.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButtonMotocykelActionPerformed

    /**
     * Tlačidlo pre vytvorenie autobusu.
     * @param evt 
     */
    private void jToggleButtonAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutobusActionPerformed
        NovyAutobusDialog autobusDialog = new NovyAutobusDialog(null, true);
                autobusDialog.setLocationRelativeTo(null);
                autobusDialog.setVisible(true);
                kategoria = autobusDialog.getAutobus();
                if(kategoria != null) {
                    jLabel9.setText("Kategória úspešne pridaná");
                    jLabel9.setVisible(true);
                    jButtonUlozitInzerat.setEnabled(true);
                }
    }//GEN-LAST:event_jToggleButtonAutobusActionPerformed

    /**
     * Tlačidlo pre vytvorenie nákladného auta.
     * @param evt 
     */
    private void jToggleButtonNakladneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonNakladneActionPerformed
        NovyNakladakDialog nakladneDialog = new NovyNakladakDialog(null, true);
                nakladneDialog.setLocationRelativeTo(null);
                nakladneDialog.setVisible(true);
                kategoria = nakladneDialog.getNakladne();
                if(kategoria != null){
                    jLabel9.setText("Kategória úspešne pridaná");
                    jLabel9.setVisible(true);
                    jButtonUlozitInzerat.setEnabled(true);
                }
    }//GEN-LAST:event_jToggleButtonNakladneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupKategoria;
    private javax.swing.JButton jButtonHladaj;
    private javax.swing.JButton jButtonNovyPredajca;
    private javax.swing.JButton jButtonObnovit;
    private javax.swing.JButton jButtonPridajExistujuceho;
    private javax.swing.JButton jButtonUlozitInzerat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDetail;
    private javax.swing.JLabel jLabelDetailText;
    private javax.swing.JLabel jLabelHlaska;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableExistujuciPredajcovia;
    private javax.swing.JTextField jTextFieldHladany;
    private javax.swing.JToggleButton jToggleButtonAutobus;
    private javax.swing.JToggleButton jToggleButtonAutomobil;
    private javax.swing.JToggleButton jToggleButtonMotocykel;
    private javax.swing.JToggleButton jToggleButtonNakladne;
    // End of variables declaration//GEN-END:variables
}
